export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
export const TOGGLE_CHECKOUT = 'TOGGLE_CHECKOUT';
export const UPDATE_PIZZA_RESULTS = 'UPDATE_PIZZA_RESULTS';
export const PLACE_ORDER = 'PLACE_ORDER';

export const SET_ADDRESSES = 'SET_ADDRESSES';
export const LOAD_MY_ORDERS = 'LOAD_MY_ORDERS';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const ADD_ADDRESS_SUCCESSFUL = 'ADD_ADDRESS_SUCCESSFUL';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
